[build-system]
requires = ["setuptools>=77", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "aristoteles"
description = "wview-to-HDF5 converter"
readme = "README.md"
requires-python = ">=3.8"
authors = [{name = "The CHIME Collaboration", email = "dvw@phas.ubc.ca"}]
license = "GPL-3.0-only"
dependencies = [
    "arrow >= 1.0",
    "click",
    "configobj",
    "h5py >= 2.10.0",
    "numpy >= 1.16",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/chime-experiment/aristoteles"

[project.scripts]
aristoteles = "aristoteles.aristoteles:entry"

[tool.setuptools.packages.find]
include = ["aristoteles*"]

[tool.setuptools_scm]
